<?php
/**
 * @file
 * Code for the GSB Feature Media Mention Display feature.
 */

include_once 'gsb_feature_media_mention_display.features.inc';

/**
 * Implements hook_preprocess_views_view
 *
 * Override more link to show link to filter page without filter parameters;
 */
function gsb_feature_media_mention_display_preprocess_views_view(&$vars) {
  if ($vars['view']->name == 'media_mention_filters' && $vars['view']->current_display == 'media_mention_by_id_or_tag') {
    $more_url = $vars['view']->display['media_mention_by_id_or_tag']->display_options['link_url'];
    $more_text = $vars['view']->display['media_mention_by_id_or_tag']->display_options['use_more_text'];
    $vars['more'] = theme('views_more', array('more_url' => '/' . $more_url, 'link_text' => check_plain($more_text), 'view' => $vars['view']));
  }
}

/**
 * Implements hook_fieldable_panels_pane_view().
 */
function gsb_feature_media_mention_display_fieldable_panels_pane_view($entity, $view_mode, $langcode) {
  $show = FALSE;
  // Check if this is a BI node.
  if ($node = menu_get_object()) {
    $show = $node->type == 'business_insight';
  }
  // Check if this is a BI landing page.
  else {
    $item = menu_get_item();
    $show = $item['path'] == 'business-insights';
  }

  // Check if this is a media_mention existing node.
  $wrapper = entity_metadata_wrapper('fieldable_panels_pane', $entity);
  if (!$show || $wrapper->getBundle() != 'existing_node' || $wrapper->field_existing_node_fpp_ref->getBundle() != 'media_mention') {
    return;
  }

  $entity->content['gsb_feature_media_mention_display_top_bar'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'top-bar',
      ),
    ),
    'link' => array(
      '#type' => 'link',
      '#title' => t('Media Mentions'),
      '#href' => "newsroom/media-mentions",
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form().
 */
function gsb_feature_media_mention_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'media_mention_filters') {
    // Exclude the search text field from auto-submit.
    $form['search']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
  }
}
